export const MEDICAL_COLOR_BRAND_PRIMARY_DARKEST = "#005865";
export const MEDICAL_COLOR_BRAND_PRIMARY_DARK = "#0096AD";
export const MEDICAL_COLOR_BRAND_PRIMARY_MEDIUM = "#00B0CA";
export const MEDICAL_COLOR_BRAND_PRIMARY_LIGHT = "#99DFEA";
export const MEDICAL_COLOR_BRAND_PRIMARY_LIGHTEST = "#E6F8FA";

export const MEDICAL_COLOR_BRAND_SECONDARY_DARKEST = "#617005";
export const MEDICAL_COLOR_BRAND_SECONDARY_DARK = "#92A708";
export const MEDICAL_COLOR_BRAND_SECONDARY_MEDIUM = "#C2DF0A";
export const MEDICAL_COLOR_BRAND_SECONDARY_LIGHT = "#E7F29D";
export const MEDICAL_COLOR_BRAND_SECONDARY_LIGHTEST = "#F9FCE7";

export const MEDICAL_COLOR_COMPLEMENTARY_DARKEST = "#290F42";
export const MEDICAL_COLOR_COMPLEMENTARY_DARK = "#3D1763";
export const MEDICAL_COLOR_COMPLEMENTARY_MEDIUM = "#511E84";
export const MEDICAL_COLOR_COMPLEMENTARY_LIGHT = "#B9A5CE";
export const MEDICAL_COLOR_COMPLEMENTARY_LIGHTEST = "#EEE9F3";

export const MEDICAL_COLOR_FEEDBACK_SUCCESS_DARKEST = "#004214";
export const MEDICAL_COLOR_FEEDBACK_SUCCESS_DARK = "#00631E";
export const MEDICAL_COLOR_FEEDBACK_SUCCESS_MEDIUM = "#008428";
export const MEDICAL_COLOR_FEEDBACK_SUCCESS_LIGHT = "#99CEA9";
export const MEDICAL_COLOR_FEEDBACK_SUCCESS_LIGHTEST = "#E6FAEC";

export const MEDICAL_COLOR_FEEDBACK_INFORMATIVE_DARKEST = "#00295B";
export const MEDICAL_COLOR_FEEDBACK_INFORMATIVE_DARK = "#003D88";
export const MEDICAL_COLOR_FEEDBACK_INFORMATIVE_MEDIUM = "#0050B5";
export const MEDICAL_COLOR_FEEDBACK_INFORMATIVE_LIGHT = "#99B9E1";
export const MEDICAL_COLOR_FEEDBACK_INFORMATIVE_LIGHTEST = "#E6EFFA";

export const MEDICAL_COLOR_FEEDBACK_WARNING_DARKEST = "#803500";
export const MEDICAL_COLOR_FEEDBACK_WARNING_DARK = "#BF4F00";
export const MEDICAL_COLOR_FEEDBACK_WARNING_MEDIUM = "#FF6900";
export const MEDICAL_COLOR_FEEDBACK_WARNING_LIGHT = "#FFC399";
export const MEDICAL_COLOR_FEEDBACK_WARNING_LIGHTEST = "#FFF3EB";

export const MEDICAL_COLOR_FEEDBACK_ERROR_DARKEST = "#751414";
export const MEDICAL_COLOR_FEEDBACK_ERROR_DARK = "#AD1C1C";
export const MEDICAL_COLOR_FEEDBACK_ERROR_MEDIUM = "#E42525";
export const MEDICAL_COLOR_FEEDBACK_ERROR_LIGHT = "#F4ABAB";
export const MEDICAL_COLOR_FEEDBACK_ERROR_LIGHTEST = "#FFECEC";

export const MEDICAL_COLOR_HIGHLIGHT_DARKEST = "#617005";
export const MEDICAL_COLOR_HIGHLIGHT_DARK = "#92A708";
export const MEDICAL_COLOR_HIGHLIGHT_MEDIUM = "#C2DF0A";
export const MEDICAL_COLOR_HIGHLIGHT_LIGHT = "#E7F29D";
export const MEDICAL_COLOR_HIGHLIGHT_LIGHTEST = "#F9FCE7";

export const MEDICAL_COLOR_NEUTRAL_DARKEST = "#0D1436";
export const MEDICAL_COLOR_NEUTRAL_DARK = "#696C80";
export const MEDICAL_COLOR_NEUTRAL_MEDIUM = "#A7AFBE";
export const MEDICAL_COLOR_NEUTRAL_LIGHT = "#F5F7FA";
export const MEDICAL_COLOR_NEUTRAL_LIGHTEST = "#FFFFFF";

export const MEDICAL_COLOR_BASE_PRIMARY_DARKEST = "#005865";
export const MEDICAL_COLOR_BASE_PRIMARY_DARK = "#0096AD";
export const MEDICAL_COLOR_BASE_PRIMARY_MEDIUM = "#00B0CA";
export const MEDICAL_COLOR_BASE_PRIMARY_LIGHT = "#99DFEA";
export const MEDICAL_COLOR_BASE_PRIMARY_LIGHTEST = "#E6F8FA";

export const MEDICAL_COLOR_BASE_SECONDARY_DARKEST = "#617005";
export const MEDICAL_COLOR_BASE_SECONDARY_DARK = "#92A708";
export const MEDICAL_COLOR_BASE_SECONDARY_MEDIUM = "#C2DF0A";
export const MEDICAL_COLOR_BASE_SECONDARY_LIGHT = "#E7F29D";
export const MEDICAL_COLOR_BASE_SECONDARY_LIGHTEST = "#F9FCE7";

export const MEDICAL_COLOR_BASE_COMPLEMENTARY_DARKEST = "#290F42";
export const MEDICAL_COLOR_BASE_COMPLEMENTARY_DARK = "#3D1763";
export const MEDICAL_COLOR_BASE_COMPLEMENTARY_MEDIUM = "#511E84";
export const MEDICAL_COLOR_BASE_COMPLEMENTARY_LIGHT = "#B9A5CE";
export const MEDICAL_COLOR_BASE_COMPLEMENTARY_LIGHTEST = "#EEE9F3";

export const MEDICAL_COLOR_BASE_FEEDBACK_SUCCESS_DARKEST = "#004214";
export const MEDICAL_COLOR_BASE_FEEDBACK_SUCCESS_DARK = "#00631E";
export const MEDICAL_COLOR_BASE_FEEDBACK_SUCCESS_MEDIUM = "#008428";
export const MEDICAL_COLOR_BASE_FEEDBACK_SUCCESS_LIGHT = "#99CEA9";
export const MEDICAL_COLOR_BASE_FEEDBACK_SUCCESS_LIGHTEST = "#E6FAEC";

export const MEDICAL_COLOR_BASE_FEEDBACK_INFORMATIVE_DARKEST = "#00295B";
export const MEDICAL_COLOR_BASE_FEEDBACK_INFORMATIVE_DARK = "#003D88";
export const MEDICAL_COLOR_BASE_FEEDBACK_INFORMATIVE_MEDIUM = "#0050B5";
export const MEDICAL_COLOR_BASE_FEEDBACK_INFORMATIVE_LIGHT = "#99B9E1";
export const MEDICAL_COLOR_BASE_FEEDBACK_INFORMATIVE_LIGHTEST = "#E6EFFA";

export const MEDICAL_COLOR_BASE_FEEDBACK_WARNING_DARKEST = "#803500";
export const MEDICAL_COLOR_BASE_FEEDBACK_WARNING_DARK = "#BF4F00";
export const MEDICAL_COLOR_BASE_FEEDBACK_WARNING_MEDIUM = "#FF6900";
export const MEDICAL_COLOR_BASE_FEEDBACK_WARNING_LIGHT = "#FFC399";
export const MEDICAL_COLOR_BASE_FEEDBACK_WARNING_LIGHTEST = "#FFF3EB";

export const MEDICAL_COLOR_BASE_FEEDBACK_ERROR_DARKEST = "#751414";
export const MEDICAL_COLOR_BASE_FEEDBACK_ERROR_DARK = "#AD1C1C";
export const MEDICAL_COLOR_BASE_FEEDBACK_ERROR_MEDIUM = "#E42525";
export const MEDICAL_COLOR_BASE_FEEDBACK_ERROR_LIGHT = "#F4ABAB";
export const MEDICAL_COLOR_BASE_FEEDBACK_ERROR_LIGHTEST = "#FFECEC";

export const MEDICAL_COLOR_BASE_HIGHLIGHT_DARKEST = "#617005";
export const MEDICAL_COLOR_BASE_HIGHLIGHT_DARK = "#92A708";
export const MEDICAL_COLOR_BASE_HIGHLIGHT_MEDIUM = "#C2DF0A";
export const MEDICAL_COLOR_BASE_HIGHLIGHT_LIGHT = "#E7F29D";
export const MEDICAL_COLOR_BASE_HIGHLIGHT_LIGHTEST = "#F9FCE7";

export const MEDICAL_COLOR_BASE_NEUTRAL_DARKEST = "#0D1436";
export const MEDICAL_COLOR_BASE_NEUTRAL_DARK = "#696C80";
export const MEDICAL_COLOR_BASE_NEUTRAL_MEDIUM = "#A7AFBE";
export const MEDICAL_COLOR_BASE_NEUTRAL_LIGHT = "#F5F7FA";
export const MEDICAL_COLOR_BASE_NEUTRAL_LIGHTEST = "#FFFFFF";
